name: build
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd react-visualizer
          ls
          npm ci
      - name: Build
        run: |
          cd react-visualizer
          npm run deploy
      - name: Push
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git push origin HEAD:${GITHUB_REF}; \
