name: Test
on:
  push:
    branches:
      - main

jobs:
  react-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: cd react-visualizer
      - name: Install Dependencies
        run: |
          ls
          npm ci
      - name: Build
        run: |
          npm run deploy
          git push origin main
